# Generated by Django 3.0 on 2020-08-31 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='img',
            new_name='imgb',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='imgt',
        ),
    ]
