# Generated by Django 3.0 on 2020-08-31 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_oder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oder',
            old_name='number',
            new_name='phone_number',
        ),
    ]
