# Generated by Django 3.0 on 2020-09-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200901_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ingram',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='experience',
            new_name='your_experience',
        ),
    ]
