# Generated by Django 3.0 on 2020-09-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200902_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='image',
            new_name='myphoto',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='description',
            new_name='little_info',
        ),
    ]
