# Generated by Django 3.0 on 2020-09-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200905_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='facebook',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='review',
            name='instagram',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='review',
            name='myphoto',
            field=models.ImageField(default='static/home/default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='review',
            name='twitter',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
