# Generated by Django 3.0 on 2020-09-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200905_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='myphoto',
            field=models.ImageField(default='static/default.png', upload_to='pics'),
        ),
    ]
