# Generated by Django 3.0 on 2020-10-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20201008_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('your_experience', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
