# Generated by Django 3.0 on 2020-10-18 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20201016_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderin',
            old_name='Table_Number',
            new_name='table_number',
        ),
        migrations.AlterField(
            model_name='oder',
            name='meal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Menu'),
        ),
    ]
